// Книги для чтения по главам. Текст приводится дословно, без изменений (лицензия перевода — CC BY-NC-ND 4.0).
// blocks: { p: "абзац" } или { img: "путь", w: ширина в px, alt: "описание" }
window.BOOKS = [
  {
    id: "little-prince",
    title: "The Little Prince",
    author: "Antoine de Saint-Exupéry",
    level: "B1",
    cover: "books/little-prince/prince-planet.jpg",
    credit: "Перевод на английский: Jeff McNeill, лицензия CC BY-NC-ND 4.0 (TheVirtualLibrary.org). Оригинал и иллюстрации автора — общественное достояние.",
    chapters: [
      {
        id: "dedication", title: "Посвящение",
        blocks: [
          { img: "books/little-prince/prince-planet.jpg", w: 300, alt: "The little prince on his planet" },
          { p: "To Leon Werth" },
          { p: "I apologize to the children for dedicating this book to a grown-up. I have a good excuse: this grown-up is the best friend I have in the world. I have another good excuse: this grown-up can understand everything, even children's books. I have a third good excuse: this grown-up lives in France where he is hungry and cold. He needs to be comforted. If all these excuses are not enough, I will then dedicate this book to the child who became that grown-up. All grown-ups were first children. (But few of them remember it.) So I correct my dedication:" },
          { p: "To Leon Werth" },
          { p: "when he was a little boy." },
        ],
      },
      {
        id: "1", title: "Глава I",
        blocks: [
          { p: "When I was six years old, I once saw a magnificent picture in a book on the virgin forest called Stories of Life. It was a boa constrictor that had swallowed a wild beast. Here is a copy of the drawing." },
          { img: "books/little-prince/boa-beast.jpg", w: 320, alt: "A boa constrictor swallowing a wild beast" },
          { p: "It was written in the book, Boa constrictors swallow their whole prey without chewing. Then they can not move and they sleep during the six months of their digestion." },
          { p: "I then thought a lot about the adventures of the jungle and, in turn, succeeded, with a colored pencil, in drawing my very first drawing. It was like this:" },
          { img: "books/little-prince/drawing-1.jpg", w: 300, alt: "Drawing number one" },
          { p: "I showed my masterpiece to the grown-ups and asked them if my drawing frightened them." },
          { p: "They said, Why would a hat be scary?" },
          { p: "My drawing was not of a hat. It was a boa constrictor digesting an elephant. I then drew the inside of the boa constrictor, so that the grown-ups could understand. They always required more explanation. My second drawing was like this:" },
          { img: "books/little-prince/drawing-2.jpg", w: 300, alt: "Drawing number two" },
          { p: "The grown-ups advised me to leave aside the drawings of boa constrictors from the outside or the inside, and to interest myself instead in geography, history, calculation, and grammar. Thus, at the age of six, I abandoned a magnificent career as a painter. I had been discouraged by the failure of my first drawing and my second drawing. Grown-ups never understand anything on their own, and it is tiring for children to always have to give them explanations." },
          { p: "So I had to choose another profession. I learned to fly planes. I flew all over the world. And geography, that's right, served me well. I knew how to recognize, at first glance, China, or Arizona. It is useful if you have gone astray during the night." },
          { p: "I have had, in the course of my life, a lot of contact with many serious people. I have lived among the grown-ups. I saw them up close. It did not really improve my opinion of them." },
          { p: "When I met one that seemed to me a little lucid, I had them experience my drawing number 1, which I had preserved. I wanted to know if they could come to a real understanding. But they always replied: It's a hat. After that I spoke to them neither of boa constrictors, nor of virgin forests, nor of stars. I put myself within their reach. I talked about bridge, golf, politics, and ties. And the grown-ups were glad to know such a reasonable man." },
        ],
      },
      {
        id: "2", title: "Глава II",
        blocks: [
          { p: "So I lived alone, with no one to talk to, until a breakdown in the Sahara desert six years ago. Something had broken in my engine. And since I had neither a mechanic nor a passenger with me, I prepared to try, by myself, to make a difficult reprieve. It was a matter of life and death. I had hardly any water to drink for a week." },
          { p: "The first night I fell asleep on the sand a thousand miles from any inhabited land. I was much more isolated than a castaway on a raft in the middle of the ocean. Then you imagine my surprise, at dawn, when a funny little voice woke me up. She said:" },
          { p: "\" Please draw me a sheep !" },
          { p: "- Hein!" },
          { p: "- Draw me a sheep… \"" },
          { p: "I jumped on my feet as if I had been struck by lightning. I rubbed my eyes well. I watched. And I saw a very extraordinary little man who looked at me gravely. This is the best portrait I later managed to make of him." },
          { img: "books/little-prince/portrait.jpg", w: 340, alt: "Portrait of the little prince" },
          { p: "But my drawing, of course, is much less ravishing than the model. It is not my fault. I had been discouraged in my career as a painter by the grown-ups at the age of six, and I had learned nothing to draw, except closed boas and open boas." },
          { p: "I looked at this apparition with eyes full of astonishment. Do not forget that I was a thousand miles from any inhabited region. Now my little fellow seemed to me neither astray, nor dead of fatigue, nor dead of hunger, nor death of thirst, nor dead of fear. He had not the appearance of a child lost in the middle of the desert, a thousand miles from any inhabited region. When I finally succeeded in speaking, I said to him:" },
          { p: "\" What are you doing here ? \"" },
          { p: "And he repeated to me, very gently, as a very serious thing:" },
          { p: "\" Please draw me a sheep… \"" },
          { p: "When the mystery is too impressive, we do not dare to disobey. As absurd as it seemed to me a thousand miles from all inhabited places and in danger of death, I took out of my pocket a sheet of paper and a pen. But I remembered that I had studied geography, history, calculation and grammar, and I told the little fellow (with a little bad humor) that I did not know how to draw. He replied," },
          { p: "\" It does not matter. Draw me a sheep. \"" },
          { p: "As I had never drawn a sheep, I thought of him as one of the only two drawings of which I was capable. That of the boa closed. And I was astounded to hear the little fellow reply:" },
          { p: "\" No ! No ! I do not want an elephant in a boa. A boa is very dangerous, and an elephant is very cumbersome. My place is tight. I need a sheep. Draw me a sheep.\"" },
          { p: "I drew. Then" },
          { img: "books/little-prince/sheep-1.jpg", w: 180, alt: "The first sheep" },
          { p: "He looked attentively, then:" },
          { p: "\" No ! That one is already very ill. Do another one. \"" },
          { p: "I drew:" },
          { img: "books/little-prince/sheep-2.jpg", w: 180, alt: "The second sheep" },
          { p: "He looked attentively, then:" },
          { p: "\"No! That one is already very ill. Do another one. \"" },
          { p: "I drew:" },
          { img: "books/little-prince/sheep-3.jpg", w: 180, alt: "The third sheep" },
          { p: "My friend smiled gently, indulgently:" },
          { p: "\"You see … it's not a sheep, it's a ram. He has horns … \"" },
          { p: "So I still refused my drawing:" },
          { p: "But he was refused, like the preceding ones:" },
          { p: "\"This one is too old. I want a long-lived sheep. \"" },
          { p: "Then, for lack of patience, as I was anxious to begin the dismantling of my engine, I scribbled this drawing:" },
          { img: "books/little-prince/box.jpg", w: 260, alt: "The box" },
          { p: "Then I threw :" },
          { p: "\"That's the box. The sheep you want is in it. \"" },
          { p: "But I was much surprised to see the face of my young judge illuminated:" },
          { p: "\"That's exactly how I wanted it!\" Do you think that sheep are to be found in this country?" },
          { p: "- Why ?" },
          { p: "- Because at home it's very small …" },
          { p: "- Surely that will suffice. I gave you a tiny sheep. \"" },
          { p: "He leaned his head toward the drawing:" },
          { p: "\"Not so small as that. He fell asleep… \"" },
          { p: "And so I made the acquaintance of the little prince." },
          { img: "books/little-prince/prince-rock.jpg", w: 280, alt: "The little prince" },
        ],
      },
    ],
  },
  {
    id: "wrong-name",
    title: "The Wrong Name",
    author: "оригинальная история · coffee shop AU",
    level: "A2",
    cover: "books/wrong-name/cover.svg",
    credit: "Оригинальная история, написана специально для WordCards. Продолжение следует.",
    chapters: [
      {
        id: "1", title: "Chapter 1. The Wrong Name",
        blocks: [
          { p: "It was raining again. Vera stood in the doorway of a small café and shook the water from her hair. She was new in the city. She had one suitcase, one sketchbook and no friends here." },
          { p: "The café was warm and smelled of cinnamon. Behind the counter, a girl with short pink hair was singing along to the radio. She sang badly, but she did not care." },
          { p: "\"Hi! What can I get you?\" the girl asked." },
          { p: "\"A large latte, please.\"" },
          { p: "\"Name?\"" },
          { p: "\"Vera.\"" },
          { p: "The girl wrote something on the paper cup and smiled. Her name tag said NIKA." },
          { p: "Vera sat down by the window and opened her sketchbook. She wanted to draw the street, but her eyes kept going back to the counter. Nika was dancing a little while she made the coffee. She dropped a spoon, laughed at herself and picked it up." },
          { p: "\"Latte for... Fear!\" Nika shouted." },
          { p: "Nobody moved." },
          { p: "\"Fear? Large latte for Fear?\"" },
          { p: "Vera looked around. Then she understood. She walked to the counter, and her face was red." },
          { p: "\"I think that is mine,\" she said quietly. \"But my name is Vera. Not Fear.\"" },
          { p: "Nika looked at the cup, then at Vera, and started to laugh. \"Oh no. I am so sorry! It is the radio. It is too loud.\" She took a pen and crossed out the word. Under it she wrote: VERA (not scary at all)." },
          { p: "Vera wanted to be angry, but she could not. She smiled, took her cup and went back to her table. The coffee was the best she had ever had." },
          { p: "Outside, the rain kept falling. Inside, Vera drew a girl with pink hair, and she did not know why." },
        ],
      },
      {
        id: "2", title: "Chapter 2. The Deal",
        blocks: [
          { p: "Vera came back the next day. She told herself it was because of the coffee." },
          { p: "\"Fear! You are back,\" said Nika. Her smile was big and warm." },
          { p: "\"It is Vera.\"" },
          { p: "\"I know. I just like how your face goes red.\"" },
          { p: "Vera's face went red. Nika laughed, but it was a kind laugh." },
          { p: "The café was almost empty that morning. Nika brought the latte to the table herself and saw the open sketchbook. On the page there was the café: the counter, the old lamp, the plants in the window. And a girl with short hair, dancing." },
          { p: "\"Wait. Is that me?\"" },
          { p: "Vera closed the sketchbook quickly. \"No. Maybe. A little.\"" },
          { p: "\"It is really good,\" said Nika. Her voice was different now, softer. \"Listen. Our menu board is terrible. My boss wrote it, and nobody can read it. Could you draw a new one?\"" },
          { p: "\"I do not know...\"" },
          { p: "\"I cannot pay you money. But I can pay you in coffee. One free latte for every hour of work. It is a good deal.\"" },
          { p: "Vera thought about her small, quiet room and her empty phone. Then she looked at Nika, who was waiting with hope in her eyes." },
          { p: "\"Two lattes,\" said Vera. \"And you spell my name right.\"" },
          { p: "Nika held out her hand. \"Deal.\"" },
          { p: "Her hand was warm. Vera held it one second too long, and they both noticed." },
          { p: "That evening Vera started the menu board. She drew cups, cakes and little clouds of steam. Nika watched over her shoulder and asked a hundred questions. Where are you from? Why did you move here? Do you always bite your lip when you draw?" },
          { p: "\"You talk a lot,\" said Vera." },
          { p: "\"And you do not talk enough,\" said Nika. \"So together we are perfect.\"" },
          { p: "She said it like a joke. But neither of them laughed." },
        ],
      },
      {
        id: "3", title: "Chapter 3. Lights Out",
        blocks: [
          { p: "A week later, the menu board was almost finished. Vera worked on it every evening, after the last customers went home. She worked slowly. She did not want it to end." },
          { p: "That night there was a storm. Nika was counting the money, and Vera was painting the last letters, when the lights went out." },
          { p: "The café was suddenly dark and very quiet. No radio. No coffee machine. Only the rain on the windows." },
          { p: "\"Do not move,\" said Nika. \"I have candles somewhere.\"" },
          { p: "Vera heard a drawer open, then a small \"ouch\", then a laugh. A minute later, a little flame appeared in the dark. Nika put three candles on the table between them." },
          { p: "In the soft light, everything looked different. Nika's hair was not pink any more, it was gold. She was not loud now. She looked almost shy." },
          { p: "\"Can I tell you a secret?\" Nika asked." },
          { p: "\"Yes.\"" },
          { p: "\"I did not write your name wrong because of the radio. I heard you the first time.\"" },
          { p: "\"Then why?\"" },
          { p: "Nika looked at the candle. \"Because you looked so serious and so sad. I wanted to see you smile. And I wanted you to come and talk to me. It was a stupid idea.\"" },
          { p: "Vera's heart was beating fast. \"It was not stupid,\" she said. \"It worked.\"" },
          { p: "For a long moment nobody spoke. The rain was softer now. Nika moved her hand across the table, slowly, like a question. Vera did not move her hand away." },
          { p: "Then the lights came back on." },
          { p: "They both jumped. The radio started to play a silly, happy song, and the coffee machine made a loud noise. Nika pulled her hand back and laughed, but her face was red. For the first time, it was her face and not Vera's." },
          { p: "\"So,\" she said, \"same time tomorrow?\"" },
          { p: "Vera picked up her brush. She tried not to smile, and she failed." },
          { p: "\"Same time tomorrow.\"" },
          { p: "To be continued..." },
        ],
      },
    ],
  },
];
