// Книги для чтения по главам. Текст приводится дословно, без изменений (лицензия перевода — CC BY-NC-ND 4.0).
// blocks: { p: "абзац" } или { img: "путь", w: ширина в px, alt: "описание" }
window.BOOKS = [
  {
    id: "little-prince",
    title: "The Little Prince",
    author: "Antoine de Saint-Exupéry",
    level: "B1",
    cover: "books/little-prince/prince-planet.jpg",
    credit: "Перевод на английский: Jeff McNeill, лицензия CC BY-NC-ND 4.0 (TheVirtualLibrary.org). Оригинал и иллюстрации автора — общественное достояние.",
    chapters: [
      {
        id: "dedication", title: "Посвящение",
        blocks: [
          { img: "books/little-prince/prince-planet.jpg", w: 300, alt: "The little prince on his planet" },
          { p: "To Leon Werth" },
          { p: "I apologize to the children for dedicating this book to a grown-up. I have a good excuse: this grown-up is the best friend I have in the world. I have another good excuse: this grown-up can understand everything, even children's books. I have a third good excuse: this grown-up lives in France where he is hungry and cold. He needs to be comforted. If all these excuses are not enough, I will then dedicate this book to the child who became that grown-up. All grown-ups were first children. (But few of them remember it.) So I correct my dedication:" },
          { p: "To Leon Werth" },
          { p: "when he was a little boy." },
        ],
      },
      {
        id: "1", title: "Глава I",
        blocks: [
          { p: "When I was six years old, I once saw a magnificent picture in a book on the virgin forest called Stories of Life. It was a boa constrictor that had swallowed a wild beast. Here is a copy of the drawing." },
          { img: "books/little-prince/boa-beast.jpg", w: 320, alt: "A boa constrictor swallowing a wild beast" },
          { p: "It was written in the book, Boa constrictors swallow their whole prey without chewing. Then they can not move and they sleep during the six months of their digestion." },
          { p: "I then thought a lot about the adventures of the jungle and, in turn, succeeded, with a colored pencil, in drawing my very first drawing. It was like this:" },
          { img: "books/little-prince/drawing-1.jpg", w: 300, alt: "Drawing number one" },
          { p: "I showed my masterpiece to the grown-ups and asked them if my drawing frightened them." },
          { p: "They said, Why would a hat be scary?" },
          { p: "My drawing was not of a hat. It was a boa constrictor digesting an elephant. I then drew the inside of the boa constrictor, so that the grown-ups could understand. They always required more explanation. My second drawing was like this:" },
          { img: "books/little-prince/drawing-2.jpg", w: 300, alt: "Drawing number two" },
          { p: "The grown-ups advised me to leave aside the drawings of boa constrictors from the outside or the inside, and to interest myself instead in geography, history, calculation, and grammar. Thus, at the age of six, I abandoned a magnificent career as a painter. I had been discouraged by the failure of my first drawing and my second drawing. Grown-ups never understand anything on their own, and it is tiring for children to always have to give them explanations." },
          { p: "So I had to choose another profession. I learned to fly planes. I flew all over the world. And geography, that's right, served me well. I knew how to recognize, at first glance, China, or Arizona. It is useful if you have gone astray during the night." },
          { p: "I have had, in the course of my life, a lot of contact with many serious people. I have lived among the grown-ups. I saw them up close. It did not really improve my opinion of them." },
          { p: "When I met one that seemed to me a little lucid, I had them experience my drawing number 1, which I had preserved. I wanted to know if they could come to a real understanding. But they always replied: It's a hat. After that I spoke to them neither of boa constrictors, nor of virgin forests, nor of stars. I put myself within their reach. I talked about bridge, golf, politics, and ties. And the grown-ups were glad to know such a reasonable man." },
        ],
      },
      {
        id: "2", title: "Глава II",
        blocks: [
          { p: "So I lived alone, with no one to talk to, until a breakdown in the Sahara desert six years ago. Something had broken in my engine. And since I had neither a mechanic nor a passenger with me, I prepared to try, by myself, to make a difficult reprieve. It was a matter of life and death. I had hardly any water to drink for a week." },
          { p: "The first night I fell asleep on the sand a thousand miles from any inhabited land. I was much more isolated than a castaway on a raft in the middle of the ocean. Then you imagine my surprise, at dawn, when a funny little voice woke me up. She said:" },
          { p: "\" Please draw me a sheep !" },
          { p: "- Hein!" },
          { p: "- Draw me a sheep… \"" },
          { p: "I jumped on my feet as if I had been struck by lightning. I rubbed my eyes well. I watched. And I saw a very extraordinary little man who looked at me gravely. This is the best portrait I later managed to make of him." },
          { img: "books/little-prince/portrait.jpg", w: 340, alt: "Portrait of the little prince" },
          { p: "But my drawing, of course, is much less ravishing than the model. It is not my fault. I had been discouraged in my career as a painter by the grown-ups at the age of six, and I had learned nothing to draw, except closed boas and open boas." },
          { p: "I looked at this apparition with eyes full of astonishment. Do not forget that I was a thousand miles from any inhabited region. Now my little fellow seemed to me neither astray, nor dead of fatigue, nor dead of hunger, nor death of thirst, nor dead of fear. He had not the appearance of a child lost in the middle of the desert, a thousand miles from any inhabited region. When I finally succeeded in speaking, I said to him:" },
          { p: "\" What are you doing here ? \"" },
          { p: "And he repeated to me, very gently, as a very serious thing:" },
          { p: "\" Please draw me a sheep… \"" },
          { p: "When the mystery is too impressive, we do not dare to disobey. As absurd as it seemed to me a thousand miles from all inhabited places and in danger of death, I took out of my pocket a sheet of paper and a pen. But I remembered that I had studied geography, history, calculation and grammar, and I told the little fellow (with a little bad humor) that I did not know how to draw. He replied," },
          { p: "\" It does not matter. Draw me a sheep. \"" },
          { p: "As I had never drawn a sheep, I thought of him as one of the only two drawings of which I was capable. That of the boa closed. And I was astounded to hear the little fellow reply:" },
          { p: "\" No ! No ! I do not want an elephant in a boa. A boa is very dangerous, and an elephant is very cumbersome. My place is tight. I need a sheep. Draw me a sheep.\"" },
          { p: "I drew. Then" },
          { img: "books/little-prince/sheep-1.jpg", w: 180, alt: "The first sheep" },
          { p: "He looked attentively, then:" },
          { p: "\" No ! That one is already very ill. Do another one. \"" },
          { p: "I drew:" },
          { img: "books/little-prince/sheep-2.jpg", w: 180, alt: "The second sheep" },
          { p: "He looked attentively, then:" },
          { p: "\"No! That one is already very ill. Do another one. \"" },
          { p: "I drew:" },
          { img: "books/little-prince/sheep-3.jpg", w: 180, alt: "The third sheep" },
          { p: "My friend smiled gently, indulgently:" },
          { p: "\"You see … it's not a sheep, it's a ram. He has horns … \"" },
          { p: "So I still refused my drawing:" },
          { p: "But he was refused, like the preceding ones:" },
          { p: "\"This one is too old. I want a long-lived sheep. \"" },
          { p: "Then, for lack of patience, as I was anxious to begin the dismantling of my engine, I scribbled this drawing:" },
          { img: "books/little-prince/box.jpg", w: 260, alt: "The box" },
          { p: "Then I threw :" },
          { p: "\"That's the box. The sheep you want is in it. \"" },
          { p: "But I was much surprised to see the face of my young judge illuminated:" },
          { p: "\"That's exactly how I wanted it!\" Do you think that sheep are to be found in this country?" },
          { p: "- Why ?" },
          { p: "- Because at home it's very small …" },
          { p: "- Surely that will suffice. I gave you a tiny sheep. \"" },
          { p: "He leaned his head toward the drawing:" },
          { p: "\"Not so small as that. He fell asleep… \"" },
          { p: "And so I made the acquaintance of the little prince." },
          { img: "books/little-prince/prince-rock.jpg", w: 280, alt: "The little prince" },
        ],
      },
    ],
  },
];
